ADMIN = "Administrador"
ADMINISTRATIVO = "Departamento de Administração e Recursos Humanos"
DIRECCION = "Direcção"
FINANCIERO = "Departamento Serviços Utente - Facturação"
JURIDICO = "Departamento Serviços Utente - Licenciamento"
TECNICO = "Departamento Recursos Hídricos"
OBSERVADOR = "Observador"
BASIN_DIVISION = "Divisão"
