#!/bin/bash

source variables.ini
source fail2ban-settings/configure_apache.sh
source fail2ban-settings/configure_postgresql.sh
source fail2ban-settings/configure_redmine.sh
source fail2ban-settings/configure_ssh.sh
source fail2ban-settings/configure_wordpress.sh

# set -e: stops the script on error
# set -u: stops the script on unset variables
# set -o pipefail:  fail the whole pipeline on first error
set -euo pipefail

# Jail configuration file
JAIL_DEF="/etc/fail2ban/jail.d/defaults-debian" # Change to the distribution defaults configuration file (e.g. defaults-arch,...)
this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

reset_configuration() {
    # Removes files generated by previous configuration attempts
    if [[ -f "${JAIL_DEF}.conf" ]]; then
        rm "${JAIL_DEF}.conf"
        touch "${JAIL_DEF}.conf"
    else
        echo "Error: ${JAIL_DEF}.conf doesn't exist. Make sure to edit JAIL_DEF value in \
              fail2ban-settings/fail2ban.conf to match your distribution"
        exit 1
    fi

    if [[ -f "$JAIL_SSH" ]]; then
        rm "$JAIL_SSH"
    fi

    if [[ -f "$JAIL_APACHE" ]]; then
        rm "$JAIL_APACHE"
    fi

    if [[ -f "$JAIL_REDMINE" ]]; then
        rm "$JAIL_REDMINE"
    fi

    if [[ -f "$JAIL_WORDPRESS" ]]; then
        rm "$JAIL_WORDPRESS"
    fi

    if [[ -f "$JAIL_POSTGRESQL" ]]; then
        rm "$JAIL_POSTGRESQL"
    fi
}

default_configuration() {
    # The script bypasses jail.conf/jail.local configuration creating custom configuration files inside the jail.d for default
    # options like mail, actions, ban policy
    reset_configuration

    # Generate local configuration, only to avoid config changes on service updates
    cp "/etc/fail2ban/jail.conf" "/etc/fail2ban/jail.local"


    # Write default configuration
    local config="[DEFAULT]
        ignoreip=127.0.0.1/8 ${IGNORE}\n
        mta=${MAIL_MTA}
        sender=${MAIL_SENDER}
        destemail=${MAIL_DESTEMAIL}\n
        bantime=${DEFAULT_BANTIME}
        maxretry=${DEFAULT_MAXRETRY}
        findtime=${DEFAULT_FINDTIME}
        action=${DEFAULT_ACTION}\n"

    echo -e "${config}" | sed 's/^[\t ]*//' > "${JAIL_DEF}.local"
}

#
# Install fail2ban
apt -y install fail2ban

# Configure default options
default_configuration

# Configure enabled services
for item in "${ACTIVE_JAILS[@]}"
do
    case $item in
    SSHD)
        sshd_configuration
    ;;
    APACHE_*)
        apache_configuration "$item"
    ;;
    REDMINE)
        redmine_configuration
    ;;
    WORDPRESS)
        wordpress_configuration
    ;;
    POSTGRESQL)
        postgresql_configuration
    ;;
    *)
        echo "Error: Configuration action fot $item not defined"
    ;;
    esac
done

# Restart service
systemctl enable fail2ban
systemctl start fail2ban
fail2ban-client reload
