-- Deploy utentes:adds_schema_and_table_view_monitor to pg

BEGIN;

CREATE SCHEMA monitoring AUTHORIZATION :"owner";
REVOKE ALL ON SCHEMA monitoring from PUBLIC;

CREATE TABLE monitoring.view_monitor (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , username text
    , verb text not null
    , route_path text not null
    , duration float not null
    , created_at timestamp without time zone NOT NULL default now()
);


ALTER TABLE monitoring.view_monitor OWNER TO :"owner";
GRANT ALL ON TABLE monitoring.view_monitor TO :"owner";
REVOKE ALL ON TABLE monitoring.view_monitor FROM PUBLIC;


COMMIT;
