-- Deploy utentes:create_table_cbase_subacias to pg

BEGIN;

CREATE TABLE cbase.subacias (
    gid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT,
    area NUMERIC(10, 2),
    ara TEXT,
    divisao TEXT,
    bacia TEXT,
    rio_prin TEXT,
    long_rio NUMERIC(10, 2),
    afluentes TEXT,
    geom GEOMETRY(MULTIPOLYGON, 32737)
);
CREATE INDEX ON cbase.subacias USING GIST (geom);
REVOKE ALL ON TABLE cbase.subacias FROM PUBLIC;
GRANT SELECT ON TABLE cbase.subacias TO :base_user;




CREATE TABLE cbase_ara.subacias (
    gid int PRIMARY KEY REFERENCES cbase.subacias(gid) ON UPDATE CASCADE ON DELETE CASCADE,
    nome TEXT,
    area NUMERIC(10, 2),
    ara TEXT,
    divisao TEXT,
    bacia TEXT,
    rio_prin TEXT,
    long_rio NUMERIC(10, 2),
    afluentes TEXT,
    geom GEOMETRY(MULTIPOLYGON, 32737)

);
CREATE INDEX ON cbase_ara.subacias USING GIST (geom);
REVOKE ALL ON TABLE cbase.subacias FROM PUBLIC;
GRANT SELECT ON TABLE cbase.subacias TO :base_user;

COMMIT;
